# 2
# Make sure to have created the project folder structure that is talked about on the github and have moved this file to ~/dockerproject
version: "3.9"
services:
# Section for the postgresql setup
  database: 
    image: postgres:14
    container_name: 'postgresql'
    # Options put into posgresql at start up
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres1
        - POSTGRES_DB=testDB
    # Assigns volumes inside the container to outside the container so the data persists and can be easily accessible
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
# Secion for PHP image & apache included
  webserver:
    build: .
    container_name: 'apache'
    restart: always
    # Assigns volumes inside the container to outside the container so the data persists and can be easily accessible
    volumes:
       - /var/www/html:/var/www/html
       - /var/log/apache2:/var/log/apache2
    # Assigns port (a host port to : a container port)
    ports:
      - "1492:80"