#this playbook performs provisioning of ubuntu for splunk enterprise from scratch
# Run: ansible-playbook -i inventories/splunk-inventory.yaml splunk-enterprise-setup.yaml --ask-pass -K
- name: splunk config
  hosts: enterprise_server
  vars_prompt:
    - name: splunk_admin_password
      prompt: Please enter your new splunk admin password
      private: true

  tasks:
  - name: create the .ssh directory if it is not there
    file:
      path: "/home/{{ ansible_user }}/.ssh"
      state: directory
      mode: 0700
    
  - name: create authorized_key file
    file:
      path: "/home/{{ ansible_user }}/.ssh/authorized_keys"
      state: touch
      mode: 0644
  
  - name: copy over key block and append to authorized_keys
    blockinfile:
      dest: "/home/{{ ansible_user }}/.ssh/authorized_keys"
      block: "{{ public_key }}"
  
  - name: create sudoers dropin file for 480
    file:
      path: /etc/sudoers.d/480
      state: touch
      mode: 0400
    become: yes
  
  - name: create a drop in entry in /etc/sudoers.d/480
    blockinfile:
      dest: /etc/sudoers.d/480
      block: "{{ ansible_user }}  ALL=(ALL) NOPASSWD: ALL"
    become: yes
  
  - name: set hostname
    hostname:
      name: "{{ hostname }}"
    become: yes

  - name: add host to hosts file
    lineinfile:
      path: /etc/hosts
      line: "127.0.1.1  {{ hostname }}"
    become: yes

  - name: setup netplan
    ansible.builtin.template:
      src: files/ubuntu/netplan.yaml.j2
      dest: /etc/netplan/00-installer-config.yaml
      mode: "0644"
      owner: root
      group: root
    become: yes

### Splunk installation starts here

  - name: create splunkadmin
    ansible.builtin.user:
      name: splunkadmin
      password: "{{ splunk_admin_password | password_hash('sha512') }}"
      shell: /bin/bash
      groups: sudo
      append: yes
    become: yes

  - name: copy over enterprise deb
    ansible.builtin.copy:
      src: "files/splunk/{{ splunk_enterprise_deb }}"
      dest: "/tmp/{{ splunk_enterprise_deb }}"
      owner: root
      group: root
      mode: '0774'
    become: true

  - name: install splunk with enterprise deb
    ansible.builtin.apt:
      deb: "/tmp/{{ splunk_enterprise_deb }}"
    become: true

  - name: copy over user seed
    ansible.builtin.template:
      src: "files/splunk/user-seed.j2"
      dest: /opt/splunk/etc/system/local/user-seed.conf
      owner: root
      group: root
      mode: '0644'
    become: true

  - name: install unix/linux addon
    ansible.builtin.unarchive:
      src: files/splunk/splunk-add-on-for-unix-and-linux_880.tgz
      dest: /opt/splunk/etc/apps
    become: true
  
  - name: create necessary local folder for addon if not there
    file:
      path: /opt/splunk/etc/apps/Splunk_TA_nix/local
      state: directory
      mode: 0700
    become: true

  - name: setup to receive information from *nix (copy inputs.conf)
    ansible.builtin.template:
      src: files/splunk/unix_inputs.conf.j2
      dest: /opt/splunk/etc/apps/Splunk_TA_nix/local/inputs.conf
      owner: root
      group: root
      mode: '0644'
    become: true

  - name: add an index named {{ splunk_group }}
    ansible.builtin.blockinfile:
      path: /opt/splunk/etc/system/local/indexes.conf
      block: |
        [{{ splunk_group }}]
        homePath = $SPLUNK_DB/{{ splunk_group }}/db
        coldPath = $SPLUNK_DB/{{ splunk_group }}/colddb
        thawedPath = $SPLUNK_DB/{{ splunk_group }}/thaweddb
      create: true
      owner: root
      group: root
      mode: '0644'
    become: true
  
  - name: add reciever on TCP 9997 (copy inputs.conf)
    ansible.builtin.copy:
      src: files/splunk/inputs.conf
      dest: /opt/splunk/etc/system/local/inputs.conf
      owner: root
      group: root
      mode: '0644'
    become: true
  
  # Needed since default free space turns an error and messes stuff up
  - name: set the minimum free space
    ansible.builtin.lineinfile:
      path: /opt/splunk/etc/system/default/server.conf
      search_string: 'minFreeSpace = 5000'
      line: minFreeSpace = 50
      owner: root
      group: root
      mode: '0644'
    become: true

  - name: change ownership to splunkadmin
    ansible.builtin.file:
      path: /opt/splunk
      state: directory
      recurse: yes
      owner: splunkadmin
      group: splunkadmin
    become: true

  - name: enable splunk
    ansible.builtin.shell: /opt/splunk/bin/splunk enable boot-start -user splunkadmin --accept-license --answer-yes --no-prompt
    become: true

  - name: bounce the box
    shell: "sleep 5 && shutdown -r"
    become: yes
    async: 1
    poll: 0
