# run: ansible-playbook windows-domain-add.yml --ask-pass -K -i inventories/windows-m10.yaml
- name: add windows host to domain
  hosts: desktop
  vars_prompt:
    - name: adminpassword
      prompt: "Please enter your ansible user password"
      private: true

  tasks:
  - name: add to domain/set hostname
    ansible.windows.win_domain_membership:
      dns_domain_name: blue1.local
      hostname: "{{ hostname }}"
      domain_admin_user: "{{ ansible_user }}"
      domain_admin_password: "{{ adminpassword }}"
      domain_ou_path: "OU=Workstations,OU=Computers,OU=blue1,DC=blue1,DC=local"
      state: domain
    register: domain_state

  - name: reboot if needed
    ansible.windows.win_reboot:
    when: domain_state.reboot_required