# run with: ansible-playbook windows-user-groups.yml --ask-pass -K -i inventories/windows-m10.yaml
# assumes that "active-directory-setup.yml" has been run with the default ou.txt
- name: add users/groups csv
  hosts: domain_controller
  tasks:
    # syntax for accessing column in register variable (list) is "{{ item.column }}" so the Name column would be "{{ item.Name }}" in a loop
  - name: "read csv '{{ csv_path }}'"
    community.general.read_csv:
      path: "{{ csv_path }}"
    register: usersandgroups
    delegate_to: localhost

  - name: "read csv '{{ group_csv_path }}'"
    community.general.read_csv:
      path: "{{ group_csv_path }}"
    register: windows_groups
    delegate_to: localhost
  
  - name: create domain groups
    community.windows.win_domain_group:
      name: "{{ item.Group }}"
      scope: domainlocal
      organizational_unit: OU=Groups,OU=Accounts,OU=blue1,DC=blue1,DC=local
    loop: "{{ windows_groups.list }}"
    # no_log: true
  
  - name: create domain users
    community.windows.win_domain_user:
      name: "{{ item.Name }}"
      password: "{{ item.Password }}"
      state: present
      groups: 
        - "{{ item.Group }}"
        - Domain Users
      path: OU=Accounts,OU=blue1,DC=blue1,DC=local
    loop: "{{ usersandgroups.list }}"
    # use this to silence output
    # no_log: true