# Needs https://github.com/ansible-collections/vyos.vyos
- name: Open firewall
  hosts: edge01
  vars_files:
      - ./secrets.yml
  vars:
    ansible_user: vyos
    ansible_password: "{{ vyospass }}"
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: vyos.vyos.vyos
  tasks:
    - vyos.vyos.vyos_command:
        commands:
        - configure
        - set firewall name DMZ-to-WAN rule 999 action accept
        - set firewall name DMZ-to-WAN rule 999 source address 172.16.50.3
        - commit

- name: Setup nginx
  hosts: nginx-oliver
  vars_files: 
      - ./secrets.yml
  # Needs the become password for sudo
  vars:
    ansible_user: "{{ nginxrootuser }}"
    ansible_password: "{{ nginxrootpass }}"
    ansible_become_pass: "{{ nginxrootpass }}"
  become: yes
  tasks:
    - name: Setup netplan
      ansible.builtin.template:
        src: ../templates/netplan.yaml.j2
        dest: /etc/netplan/00-installer-config.yaml
        mode: "0644"
        owner: root
        group: root

    - name: Apply netplan
      ansible.builtin.shell: |
        netplan apply

    - name: "Set hostname as {{ hostname }}"
      ansible.builtin.hostname:
        name: "{{ hostname }}"

    - name: "Create {{ nginxuser }}"
      ansible.builtin.user:
        name: "{{ nginxuser }}"
        password: "{{ nginxpass | password_hash('sha512') }}"
        shell: /bin/bash
        groups: sudo
        append: yes
    
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        update_cache: yes

    - name: Add banner
      ansible.builtin.shell: |
        echo 'nginx01-oliver' > /var/www/html/index.html
    
    - name: Start nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
    
    - name: Wazuh
      ansible.builtin.shell: |
        curl -so wazuh-agent-4.3.10.deb https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.3.10-1_amd64.deb
        WAZUH_MANAGER='172.16.200.10' WAZUH_AGENT_GROUP='linux' dpkg -i ./wazuh-agent-4.3.10.deb
        systemctl daemon-reload
        systemctl enable wazuh-agent
        systemctl start wazuh-agent

# Needs https://github.com/ansible-collections/vyos.vyos
- name: Close firewall
  hosts: edge01
  vars_files:
      - ./secrets.yml
  vars:
    ansible_user: vyos
    ansible_password: "{{ vyospass }}"
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: vyos.vyos.vyos
  tasks:
    - vyos.vyos.vyos_command:
        commands:
        - configure
        - delete firewall name DMZ-to-WAN rule 999
        - commit