---
- name: nginx for SYS265
  hosts: D78
  become: true
  tasks:
    - name: Install NGINX from source
      include_role:
        name: nginxinc.nginx
      vars:
        nginx_debug_output: true

        nginx_install_from: source
        nginx_branch: stable
        nginx_static_modules: ['http_ssl_module']
        nginx_install_source_build_tools: true
        nginx_install_source_pcre: true
        nginx_install_source_openssl: true
        nginx_install_source_zlib: true
        
    - name: Adding Firewall rule for nginx
      firewalld:
              port: 80/tcp
              permanent: true
              state: enabled
    
    - name: Reload Firewall
      systemd:
              name: firewalld
              state: reloaded
