- name: Install Windows Applications
  hosts: windows
  tasks:
          - name: Install Firefox, 7zip, and Notepad++
            win_chocolatey:
                    name:
                            - firefox
                            - 7zip
                            - notepadplusplus
                    state: present
